spring:
  docker:
    compose:
      enabled: true
      file: classpath:/compose-mongodb.yaml
      skip:
        in-tests: false
  data:
    mongodb:
      auto-index-creation: true
      database: dummy-mongo
      host: software-factory-mongo
      port: 27017

mongock:
  enabled: true
  migration-scan-package:
    - io.positivinh.virtuoso.data.mongodb.dummy.migrations

virtuoso:
  mongodb:
    repositories:
      base-package: io.positivinh.virtuoso.data.mongodb.dummy.repository