spring:
  docker:
    compose:
      enabled: true
      file: classpath:/compose-mongodb.yaml
      skip:
        in-tests: false
  data:
    mongodb:
      auto-index-creation: true
      database: dummy-mongo
      host: software-factory-mongo
      port: 27017

positivinh:
  mongodb:
    repositories:
      base-package: io.positivinh.softwarefactory.data.mongodb.dummy.repository